services:
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:1.27.3-alpine
    volumes:
      - ./docker/nginx/prod:/etc/nginx/conf.d/
    networks:
      - web_network
      - traefik_net
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"

      # HTTP Router (port 80) - redirect to HTTPS
      - "traefik.http.routers.humblebrains-web.rule=Host(`humblebrains.ru`) || Host(`www.humblebrains.ru`)"
      - "traefik.http.routers.humblebrains-web.entrypoints=web"
      - "traefik.http.routers.humblebrains-web.middlewares=redirect-to-https@file"

      # HTTPS Router (port 443) - serve TLS
      - "traefik.http.routers.humblebrains-secure.rule=Host(`humblebrains.ru`) || Host(`www.humblebrains.ru`)"
      - "traefik.http.routers.humblebrains-secure.entrypoints=websecure"
      - "traefik.http.routers.humblebrains-secure.tls.certresolver=myresolver"

  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./
      dockerfile: ./docker/prod.Dockerfile
      args:
        API_URL: ${API_URL}
    image: ${DOCKER_USERNAME}/${APP_NAME}:app-${COMMIT_TAG}
    networks:
      - web_network

networks:
  web_network:
  traefik_net:
    external: true